#define TMRCTR_DEVICE_ID  XPAR_TMRCTR_0_DEVICE_ID
#define TIMER_COUNTER_0   0
#define TIMER_COUNTER_1   1

#define PARTIAL_SHIFT_RIGHT_RM_SIZE         (0x5D6A0)
#define PARTIAL_SHIFT_LEFT_RM_SIZE          (0x5D6A0)
#define PARTIAL_COUNT_UP_RM_SIZE            (0xB3818)
#define PARTIAL_COUNT_DOWN_RM_SIZE          (0xB3818)
#define PARTIAL_SHIFT_RIGHT_PFCRC_RM_SIZE   (0x62638)
#define PARTIAL_SHIFT_LEFT_PFCRC_RM_SIZE    (0x62638)
#define PARTIAL_COUNT_UP_PFCRC_RM_SIZE      (0xBD120)
#define PARTIAL_COUNT_DOWN_PFCRC_RM_SIZE    (0xBD120)

#define PARTIAL_SHIFT_LEFT_ADDR             (0x0)
#define PARTIAL_SHIFT_RIGHT_ADDR            (0x60000)
#define PARTIAL_COUNT_UP_ADDR               (0xC0000)
#define PARTIAL_COUNT_DOWN_ADDR             (0x180000)
#define PARTIAL_SHIFT_LEFT_PFCRC_ADDR       (0x240000)
#define PARTIAL_SHIFT_RIGHT_PFCRC_ADDR      (0x2B0000)
#define PARTIAL_COUNT_UP_PFCRC_ADDR         (0x320000)
#define PARTIAL_COUNT_DOWN_PFCRC_ADDR       (0x3E0000)

#define PARTIAL_DDR_SHIFT_LEFT_ADDR         XPAR_MIG_0_C0_DDR4_MEMORY_MAP_BASEADDR+PARTIAL_SHIFT_LEFT_ADDR
#define PARTIAL_DDR_SHIFT_RIGHT_ADDR        XPAR_MIG_0_C0_DDR4_MEMORY_MAP_BASEADDR+PARTIAL_SHIFT_RIGHT_ADDR
#define PARTIAL_DDR_COUNT_UP_ADDR           XPAR_MIG_0_C0_DDR4_MEMORY_MAP_BASEADDR+PARTIAL_COUNT_UP_ADDR
#define PARTIAL_DDR_COUNT_DOWN_ADDR         XPAR_MIG_0_C0_DDR4_MEMORY_MAP_BASEADDR+PARTIAL_COUNT_DOWN_ADDR

#define XDFXC_DEVICE_ID                     XPAR_HIER_DFXC_DFX_CONTROLLER_DEVICE_ID
#define XDFXC_VS_SHIFT_ID                   XPAR_HIER_DFXC_DFX_CONTROLLER_VS_SHIFT_ID
#define XDFXC_VS_COUNT_ID                   XPAR_HIER_DFXC_DFX_CONTROLLER_VS_COUNT_ID
#define XDFXC_VS_SHIFT_RM_SHIFT_RIGHT_ID    XPAR_HIER_DFXC_DFX_CONTROLLER_VS_SHIFT_RM_SHIFT_RIGHT_ID
#define XDFXC_VS_SHIFT_RM_SHIFT_LEFT_ID     XPAR_HIER_DFXC_DFX_CONTROLLER_VS_SHIFT_RM_SHIFT_LEFT_ID
#define XDFXC_VS_COUNT_RM_COUNT_UP_ID       XPAR_HIER_DFXC_DFX_CONTROLLER_VS_COUNT_RM_COUNT_UP_ID
#define XDFXC_VS_COUNT_RM_COUNT_DOWN_ID     XPAR_HIER_DFXC_DFX_CONTROLLER_VS_COUNT_RM_COUNT_DOWN_ID
