
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xttcps.h"

/*
* The configuration table for devices
*/

XTtcPs_Config XTtcPs_ConfigTable[] =
{
	{
		XPAR_PSU_TTC_6_DEVICE_ID,
		XPAR_PSU_TTC_6_BASEADDR,
		XPAR_PSU_TTC_6_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PSU_TTC_7_DEVICE_ID,
		XPAR_PSU_TTC_7_BASEADDR,
		XPAR_PSU_TTC_7_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PSU_TTC_8_DEVICE_ID,
		XPAR_PSU_TTC_8_BASEADDR,
		XPAR_PSU_TTC_8_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PSU_TTC_9_DEVICE_ID,
		XPAR_PSU_TTC_9_BASEADDR,
		XPAR_PSU_TTC_9_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PSU_TTC_10_DEVICE_ID,
		XPAR_PSU_TTC_10_BASEADDR,
		XPAR_PSU_TTC_10_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PSU_TTC_11_DEVICE_ID,
		XPAR_PSU_TTC_11_BASEADDR,
		XPAR_PSU_TTC_11_TTC_CLK_FREQ_HZ
	}
};


