#define TMRCTR_DEVICE_ID  XPAR_TMRCTR_0_DEVICE_ID
#define TIMER_COUNTER_0   0
#define TIMER_COUNTER_1   1

#define PARTIAL_COUNT_DOWN_RM_SIZE          (0xF4510)//(0x226798)
#define PARTIAL_COUNT_UP_RM_SIZE            (0xF4510)//(0x226798)
#define PARTIAL_SHIFT_LEFT_RM_SIZE          (0xF4510)//(0x226798)
#define PARTIAL_SHIFT_RIGHT_RM_SIZE         (0xF4510)//(0x226798)


#define PARTIAL_COUNT_DOWN_ADDR         (0x00000000)
#define PARTIAL_COUNT_UP_ADDR           (0x00400000)
#define PARTIAL_SHIFT_LEFT_ADDR         (0x00800000)
#define PARTIAL_SHIFT_RIGHT_ADDR        (0x00C00000)

/*#define PARTIAL_DDR_COUNT_DOWN_ADDR         (0x70000000)
#define PARTIAL_DDR_COUNT_UP_ADDR           (0x70400000)
#define PARTIAL_DDR_SHIFT_LEFT_ADDR         (0x70800000)
#define PARTIAL_DDR_SHIFT_RIGHT_ADDR        (0x70C00000)*/

                                             

#define PARTIAL_DDR_SHIFT_LEFT_ADDR         XPAR_MIG_0_C0_DDR4_MEMORY_MAP_BASEADDR+PARTIAL_SHIFT_LEFT_ADDR
#define PARTIAL_DDR_SHIFT_RIGHT_ADDR        XPAR_MIG_0_C0_DDR4_MEMORY_MAP_BASEADDR+PARTIAL_SHIFT_RIGHT_ADDR
#define PARTIAL_DDR_COUNT_UP_ADDR           XPAR_MIG_0_C0_DDR4_MEMORY_MAP_BASEADDR+PARTIAL_COUNT_UP_ADDR
#define PARTIAL_DDR_COUNT_DOWN_ADDR         XPAR_MIG_0_C0_DDR4_MEMORY_MAP_BASEADDR+PARTIAL_COUNT_DOWN_ADDR


#define XDFXC_DEVICE_ID                     XPAR_ISO_SHELL_HIER_DFXC_DFX_CONTROLLER_0_DEVICE_ID
#define XDFXC_VS_SHIFT_ID                   XPAR_ISO_SHELL_HIER_DFXC_DFX_CONTROLLER_0_VS_SHIFT_ID
#define XDFXC_VS_COUNT_ID                   XPAR_ISO_SHELL_HIER_DFXC_DFX_CONTROLLER_0_VS_COUNT_ID
#define XDFXC_VS_SHIFT_RM_SHIFT_RIGHT_ID    XPAR_ISO_SHELL_HIER_DFXC_DFX_CONTROLLER_0_VS_SHIFT_RM_SHIFT_RIGHT_ID
#define XDFXC_VS_SHIFT_RM_SHIFT_LEFT_ID     XPAR_ISO_SHELL_HIER_DFXC_DFX_CONTROLLER_0_VS_SHIFT_RM_SHIFT_LEFT_ID
#define XDFXC_VS_COUNT_RM_COUNT_UP_ID       XPAR_ISO_SHELL_HIER_DFXC_DFX_CONTROLLER_0_VS_COUNT_RM_COUNT_UP_ID
#define XDFXC_VS_COUNT_RM_COUNT_DOWN_ID     XPAR_ISO_SHELL_HIER_DFXC_DFX_CONTROLLER_0_VS_COUNT_RM_COUNT_DOWN_ID

#define PARTIAL_DDR_1_COUNT_DOWN_ADDR   XPAR_PSU_DDR_1_S_AXI_BASEADDR+PARTIAL_COUNT_DOWN_ADDR
#define PARTIAL_DDR_1_COUNT_UP_ADDR     XPAR_PSU_DDR_1_S_AXI_BASEADDR+PARTIAL_COUNT_UP_ADDR
#define PARTIAL_DDR_1_SHIFT_LEFT_ADDR   XPAR_PSU_DDR_1_S_AXI_BASEADDR+PARTIAL_SHIFT_LEFT_ADDR
#define PARTIAL_DDR_1_SHIFT_RIGHT_ADDR   XPAR_PSU_DDR_1_S_AXI_BASEADDR+PARTIAL_SHIFT_RIGHT_ADDR
